apiVersion: v1
kind: Service
metadata:
  name: xops-app-svc
  labels:
    app: xops-app
spec:
  selector:
    app: xops-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
